name: Application Build and Test

on:
  push:
    branches:
      - main

jobs:
  app-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker version

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Run Services with Docker Compose
      run: |
        docker-compose up -d --build

    - name: Test API Endpoints
      run: |
        sleep 10
        curl -f http://localhost:8080/api/items || echo "API Test Failed"

    - name: Clean up
      if: always()
      run: |
        docker-compose down
